---
- hosts: localhost
  vars_files:
    - "./vars/main.yaml"
  vars_prompt:
    - name: hostname
      prompt: "what is your hostname?"
  tasks:
    - name: add wireguard ppa
      become: yes
      when: ansible_os_family == "Debian"
      apt_repository:
        repo: ppa:wireguard/wireguard

    - name: install wireguard
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: wireguard

    - name: Create Public and Private Keys
      shell: wg genkey | tee ~/privatekey | wg pubkey > ~/publickey
      args:
        creates: ~/publickey

    - name: store public key in repo
      fetch:
        src: ~/publickey
        flat: yes
        dest: ./files/publickeys/{{hostname}}

    - name: read private key
      slurp:
        src: ~/privatekey
      register: privateKey

    - name: generate wireguard config
      become: yes
      template:
        src: ./files/client.conf
        dest: /etc/wireguard/subspace.conf

    - name: start wireguard interface
      become: yes
      systemd:
        name: wg-quick@subspace
        enabled: yes
        state: restarted
