---
- hosts: all
  remote_user: kevindurb

  tasks:

    - name: Create Public and Private Keys
      shell: wg genkey | tee ~/privatekey | wg pubkey > ~/publickey
      args:
        creates: ~/publickey

    - name: Read Public Key
      slurp:
        src: ~/publickey
      register: publickey

    - debug:
        msg: "{{ publickey['content'] | b64decode }}"
