---
- hosts: all
  remote_user: kevindurb
  tasks:
    - name: add wireguard ppa
      become: yes
      apt_repository:
        repo: ppa:wireguard/wireguard

    - name: install wireguard
      become: yes
      apt:
        name: wireguard

    - name: Create Public and Private Keys
      shell: wg genkey | tee ~/privatekey | wg pubkey > ~/publickey
      args:
        creates: ~/publickey

    - name: pull ssh key back to controller
      fetch:
        src: ~/publickey
        flat: yes
        dest: ./files/publickeys/{{inventory_hostname}}

- hosts: worldbastion
  remote_user: kevindurb
  tasks:
    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

- hosts: all
  remote_user: kevindurb
  vars_files:
    - "./vars/main.yaml"
  tasks:
    - name: read private key
      slurp:
        src: ~/privatekey
      register: privateKey

    - name: generate wireguard config
      become: yes
      template:
        src: ./files/subspace.conf
        dest: /etc/wireguard/subspace.conf

    - name: start wireguard interface
      become: yes
      systemd:
        name: wg-quick@subspace
        enabled: yes
        state: restarted
